name: php-cs-fixer

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      - run: npm run build

      - name: Run performance script
        run: node test/benchBSON.mjs

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update perf results
          file_pattern: perf.md
